web:
  build: ./docker
  volumes:
    - "./app:/home/noroot/app"
  ports:
    - "3000:3000"
  dns: 8.8.8.8
  links:
    - db
    - mail

db:
  image: mongo
  volumes:
    - "./docker/data:/data"

mail:
  image: mailhog/mailhog
  ports:
      - "8025:8025"